### PR TITLE
feat(#10): add optional value for validations rules

### PR DESCRIPTION
**Pull request by yoannfleurydev**

### CODE REVIEW

**Comment by ivan-dalmet** [comment]
I think we should allow all rules (except isRequired) to accept `null`, `undefined` or `""`

**Comment by yoannfleurydev** [comment]
I'm on it. Pinging you back today when it's OK :+1:.

**Comment by yoannfleurydev** [comment]
Update done, any feedback is welcome. 😃

**Comment by ivan-dalmet** [comment]
@yoannfleurydev just add some missing cases, can you check the new commit?

**Pull request merged**
